// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';
export const USER_UPDATED_SUCCESS = 'USER_UPDATED_SUCCESS';

// Message actions
export const MESSAGE_ON_LOADED = 'MESSAGE_ON_LOADED';

// Room actions
export const ROOM_ON_LOADED = 'ROOM_ON_LOADED';
export const ROOM_SET_CURRENT = 'ROOM_SET_CURRENT';
export const ROOM_ON_LOADED_USERS = 'ROOM_ON_LOADED_USERS';
export const ROOM_ENTER_SUCCESS = 'ROOM_ENTER_SUCCESS';
export const ROOM_LEAVE_SUCCESS = 'ROOM_LEAVE_SUCCESS';
