// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Chatrooms actions
export const CHATROOM_CREATED_SUCCESS = 'CHATROOM_CREATED_SUCCESS';
export const CHATROOM_JOINED_SUCCESS = 'CHATROOM_JOINED_SUCCESS';
export const CHATROOM_LEFT_SUCCESS = 'CHATROOM_LEFT_SUCCESS';
export const UPDATE_CHATROOMS = 'UPDATE_CHATROOMS';
export const GET_CHATROOMS_REQUESTED = 'GET_CHATROOMS_REQUESTED';
export const GET_CHATROOMS_REJECTED = 'GET_CHATROOMS_REJECTED';
export const GET_CHATROOMS_FULFILLED = 'GET_CHATROOMS_FULFILLED';

// Messages Actions
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const UPDATE_USERS = 'UPDATE_USERS';
